name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EM_VERSION: 4.0.4
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
            version: ${{env.EM_VERSION}}
            actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Run tests
        run: uv run pytest -xvs examples/